name: Push

on: push

jobs:
  test:
    name: Lint, build, and test on node 22.x and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Test codebase
        run: yarn test
      - name: Lint codebase
        run: yarn lint
      - name: Build lib
        working-directory: lib
        run: yarn build
      - name: Build app
        working-directory: app
        run: yarn build
